### ISSUE TITLE
Python error : AttributeError: 'module' object has no attribute 'run' 

### ISSUE THREAD

**Issue by daamien** [asgeirrr/pgantomizer#1]
Hello, 

I am testing your software but I can't make it run 

When I launched:
pgantomizer_dump --schema dolibarr.yml --dbname dolibarr --user labo

I get the following error:
 
```
Traceback (most recent call last):
  File "/usr/local/bin/pgantomizer_dump", line 9, in <module>
    load_entry_point('pgantomizer==0.1.1', 'console_scripts', 'pgantomizer_dump')()
  File "/usr/local/lib/python3.4/dist-packages/pgantomizer/dump.py", line 53, in main
    if args.dbname and args.user else [])
  File "/usr/local/lib/python3.4/dist-packages/pgantomizer/dump.py", line 23, in dump_db
    subprocess.run(cmd, shell=True)
AttributeError: 'module' object has no attribute 'run'
```

I'm running it on Debian 8 jessie with Python 3.4.2

**Comment by asgeirrr** [comment]
Hi, thanks for trying it out. The problem is the `subprocess` library in Python 3.4 does not have the `run` function, it was a Python 3.5 addition. Can you try to install a newer Python on Debian Jessie using e.g. pyenv? There is a guide here: https://gist.github.com/jaydenkieran/75b2bbc32b5b70c4fdfb161ecdb6daa2

Pgantomizer is a rather new tool and I like to use features from newer versions of Python when it helps code readability as in this case with `subprocess.run`.

**Comment by daamien** [comment]
Hi !

Thanks for your reply ! 

For some reasons, `pyenv` is scaring me a little bit so I decided to make a docker image instead... 

The Dockerfile is here, any comment is welcome:
https://github.com/daamien/pgantomizer/blob/docker/Dockerfile 

Anyway I think the README file should make it more clear that python 3.5+ is required.
